### ISSUE TITLE
Track Prysm

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNodePackage-prysm-prater#52]
Track the most important features in the road to Eth2 multiclient in DAppNode of the Prysm client.

- [x] Implement web3signer support
- [x] Implement validator remote keymanager API: https://github.com/dappnode/DAppNodePackage-prysm-prater/pull/55
- [x] Fee recipient: https://github.com/dappnode/DAppNodePackage-prysm-prater/pull/73
- [x] Checkpoint sync :rocket: https://github.com/prysmaticlabs/prysm/pull/10387
- [x] DAppNode package for Gnosis chain https://github.com/dappnode/DAppNodePackage-gnosis-beacon-chain-prysm/pull/14
- [ ] DAppNode package for mainnet
- [ ] Implement JWT

**Comment by james-prysm** [comment]
That's the Wrong PR.. this is for my testing. the fee recipient one is already merged in
