### ISSUE TITLE
Test Eth2 migration in network Prater

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNodePackage-prysm-prater#59]
**Test instructions**

Having at least 2 validators in the legacy Prysm-prater (previous version to v1.0.0) and web3signer-prater already installed, manually update Prysm-prater to the latest version.

During container start-up, there should be some logs saying "found validators, starting migration". This process will export your validator keystores, walletpassword, and slashing protection data to the web3signer via the remote keymanager API.

If there is any error during this migration, the volume will be empty, ensuring no keystores are loaded in the Prysm-prater.

Ensure this process was successfully and the keystores are loaded in the web3signer

**Test report**

With an editable unique comment report any errors and feedback you may find necessary.

If no errors leave a checkmark

**Testers**

@pablomendezroyo :heavy_check_mark: 
@3alpha
@tropicar
@mgarciate
@Pol-Lanski ✅

**Comment by Pol-Lanski** [comment]
@Pol-Lanski

**Comment by Pol-Lanski** [comment]
## Instructions to roll-back and test: 
1. If you have performed the migration before, save your keystores by exporting them (and make sure you remember the keystore password or that you have the mnemonic to regenerate them). Delete them from the web3signer.
2. Rollback prysm prater to DNP version 0.1.7 (/ipfs/QmPMhG8cd8o3sXdY3Ub8VE9m5PQjpN3YfLvfwST97DC1YE)
3. Upload the keystores to the Prysm UI.
---
You are ready to perform the migration, just update to the latest Prysm Prater version as per the UI banner.

**Comment by Pol-Lanski** [comment]
Blocked by core version 0.2.50 https://github.com/dappnode/DNP_DAPPMANAGER/releases/tag/v0.2.50
In order to test with the latest web3signer version, the CORE needs to be updated.

**Comment by mgarciate** [comment]
Worked OK on my side after PR #68 was merged.
### Steps I followed

1. I compiled and installed commit _3411031caa439bbc3d6756e09a03fd65f3d8c79e_ manually setting v1.0.6 since I couldn't install Prysm 0.1.7 due to core restrictions
2. I added 2 validators via Prysm UI
3. I compiled and installed the package and the W3S was installed too
4. Prysm + web3signer contine attesting

**Comment by mgarciate** [comment]
@pablomendezroyo @Pol-Lanski ⬆️

**Comment by Pol-Lanski** [comment]
1st test didn't work. :/ Details to Pablo in DM.
