### ISSUE TITLE
Hardcoded the JWT using the entrypoint

### ISSUE THREAD

**Issue by tropicar** [dappnode/DAppNodePackage-prysm-prater#61]
**Describe the bug**
Prysm overrides the JWT and the validator does not work.

**To Reproduce**

Steps to reproduce the behaviour:
1. Install version 2.1.2 of prysm prater
2. Go `docker exec -it DAppNodePackage-validator.prysm-prater.dnp.dappnode.eth /bin/sh`
3. Go to /root/.eth3validators/auth-token and change the value of that token
4. Restart the container
5. Check the value, the value is the same after the change, which means the data in the volume persists over the operation are done in the dockerfile(where is hardcoded the jwt).

**Expected behavior**

That token must be the same after a restart.

**Comment by pablomendezroyo** [comment]
closed by https://github.com/dappnode/DAppNodePackage-prysm-prater/pull/62
