### ISSUE TITLE
web3signer-ui does not import keys

### ISSUE THREAD

**Issue by etherni** [dappnode/DAppNodePackage-prysm-prater#65]
Some time ago I imported 3 keystores and everything was working as expected. 
Today I checked my validators and upon accessing the UI page I was redirected to the empty **Your Validator Accounts List** screen.

Prysm Prater _validator_ logs show:
`time="2022-05-30 02:23:14" level=warning msg="No validating keys fetched. Trying again" prefix=validator`

Attempt to re-import my keys end up in **Import Completed** popup with the following message:
`Error: Failed to fetch`

I tried to delete and reinstall the web3signer package - the same result.

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/4120215/170907094-3870865c-2c3f-4ac3-9eae-52f16a8405c4.png)

![image](https://user-images.githubusercontent.com/4120215/170907156-fa2ad84a-29c3-42fc-9153-36acaa3c5d4c.png)

![image](https://user-images.githubusercontent.com/4120215/170907237-ab7ea1e8-5a4e-40d9-9918-2ab2611784ab.png)

**DAppNode version:**

Core DAppNode Packages versions
bind.dnp.dappnode.eth: 0.2.6
core.dnp.dappnode.eth: 0.2.54
dappmanager.dnp.dappnode.eth: 0.2.49, commit: 14f56e8e
https.dnp.dappnode.eth: 0.1.3
ipfs.dnp.dappnode.eth: 0.2.16
vpn.dnp.dappnode.eth: 0.2.8, commit: f9a8743e
wifi.dnp.dappnode.eth: 0.2.8
System info
dockerComposeVersion: 1.25.5
dockerServerVersion: 20.10.2
dockerCliVersion: 20.10.2
os: debian
versionCodename: bullseye
architecture: amd64
kernel: 5.10.0-1-amd64
Disk usage: 81%

- Package version: Version: 0.1.4 (22.5.0 upstream)
- OS: DAppNode Advance
- Browser: Edge

**Additional context**

web3signer status is 3/4 **running** and 1/4 **restarting**

![image](https://user-images.githubusercontent.com/4120215/170906672-8d49281a-88bd-470e-a2ed-d5a67bf2a9c2.png)

**Web3signer Prater logs:**

1. UI

```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2022/05/30 01:54:47 [notice] 1#1: using the "epoll" event method
2022/05/30 01:54:47 [notice] 1#1: nginx/1.21.6
2022/05/30 01:54:47 [notice] 1#1: built by gcc 10.3.1 20211027 (Alpine 10.3.1_git20211027) 
2022/05/30 01:54:47 [notice] 1#1: OS: Linux 5.10.0-1-amd64
2022/05/30 01:54:47 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2022/05/30 01:54:47 [notice] 1#1: start worker processes
2022/05/30 01:54:47 [notice] 1#1: start worker process 33
2022/05/30 01:54:47 [notice] 1#1: start worker process 34
2022/05/30 01:54:47 [notice] 1#1: start worker process 35
2022/05/30 01:54:47 [notice] 1#1: start worker process 36
2022/05/30 01:54:47 [notice] 1#1: start worker process 37
2022/05/30 01:54:47 [notice] 1#1: start worker process 38
2022/05/30 01:54:47 [notice] 1#1: start worker process 39
2022/05/30 01:54:47 [notice] 1#1: start worker process 40
```

2. web3signer
```
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
[0.004s][warning][os,thread] Failed to start thread - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Cannot create worker GC thread. Out of system resources.
# An error report file with more information is saved as:
# /opt/web3signer/hs_err_pid7.log
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
[0.003s][warning][os,thread] Failed to start thread - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Cannot create worker GC thread. Out of system resources.
# An error report file with more information is saved as:
# /opt/web3signer/hs_err_pid7.log
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
[0.002s][warning][os,thread] Failed to start thread - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
```

**Comment by lodotek** [comment]
This one just bit me yesterday :-/
