### ISSUE TITLE
Infura backup doesn't work for Prysm Prater ("no service beacon-validator...")

### ISSUE THREAD

**Issue by etherni** [dappnode/DAppNodePackage-prysm-prater#71]
@etherni thank you for the report!

> I created a new **ETH2** project on Infura and noticed a new connection string template:

The mainnet naming was a typo, you should always use prater endpoint. You can use the same RPC endpoint for the checkpoint sync and for the web3 fallback provider

This typo was fixed by https://github.com/dappnode/DAppNodePackage-prysm-prater/pull/70

_Originally posted by @pablomendezroyo in https://github.com/dappnode/DAppNodePackage-prysm-prater/issues/60#issuecomment-1147106173_

However, Infura backup seems not working - upon specifying Infura Prater endpoint I see "no service beacon-validator..." message
![image](https://user-images.githubusercontent.com/4120215/172411869-c6ca316b-a126-43a0-9397-c77901dc6294.png)

**Comment by pablomendezroyo** [comment]
thanks for the report! 

Fixed by https://github.com/dappnode/DAppNodePackage-prysm-prater/commit/a9f608ad3aed40dacb71775c7a131f4d7a22bf23
